services:
  db:
    build: ./database
    container_name: db
    ports:
      - "8005:8005"
    volumes:
      - database-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  audit:
    build: ./Audit
    container_name: audit
    ports:
      - "8004:8004"
    volumes:
      - ./audit_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  agent:
    build: ./YandexGPTBot
    env_file:
      - ./.env
    container_name: agent
    ports:
      - "8003:8003"
    depends_on:
      - audit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./private.pem:/app/private.pem

  rag:
    build: ./RAG_model
    env_file:
      - ./.env
    volumes:
      - ./rag-data:/app/data
    container_name: rag
    ports:
      - "8002:8002"
    depends_on:
      - audit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  valid:
    build: ./Heuristic
    container_name: valid
    ports:
      - "8001:8001"
    depends_on:
      - audit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  orchestrator:
    build: ./orchestrator
    env_file:
      - ./.env
    container_name: orchestrator
    ports:
      - "8000:8000"
    depends_on:
      audit:
        condition: service_started
      valid:
        condition: service_started
      db:
        condition: service_started
      agent:
        condition: service_started
      rag:
        condition: service_started

volumes:
  rag-data:
  database-data:
